name = "veeda-wallet-backend"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# Environment variables (set via wrangler secret put)
# SUPABASE_URL
# SUPABASE_SERVICE_ROLE_KEY
# JWT_SECRET

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "your-dev-kv-namespace-id"
preview_id = "your-dev-kv-preview-id"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "your-prod-kv-namespace-id"
